CREATE TABLE IF NOT EXISTS urls(
    id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks(
    id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id INT REFERENCES urls(id),
    status_code SMALLINT,
    h1 TEXT,
    title TEXT,
    created_at DATE,
)