CREATE TABLE IF NOT EXISTS urls(
    id SERIAL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url_id INT REFERENCES urls(id) ON DELETE CASCADE,
    status_code SMALLINT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);